name       : glib2
version    : 2.56.3
release    : 46
source     :
    - https://download.gnome.org/sources/glib/2.56/glib-2.56.3.tar.xz : a9a4c5b4c81b6c75bc140bdf5e32120ef3ce841b7413214ecf5f987acec74cb2
license    : LGPL-2.1-or-later
summary    : Low level C library containing data structure handling and interfaces
component  : system.base
builddeps  :
    - pkgconfig32(libelf)
    - pkgconfig32(libffi)
    - pkgconfig32(libpcre)
    - pkgconfig32(mount)
    - pkgconfig32(zlib)
emul32     : yes
description: |
    GLib is the low-level core library that forms the basis for projects such as GTK+ and GNOME. It provides data structure handling for C, portability wrappers, and interfaces for such runtime functionality as an event loop, threads, dynamic loading, and an object system.
setup      : |
    %apply_patches
    %configure --prefix=/usr \
               --with-pcre=system \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    # Allow emul32 to work correctly.
    install -m 00644 $pkgfiles/glibconfig.h $installdir/usr/include/glib-2.0/glibconfig.h
