name       : glib2
version    : 2.76.4
release    : 96
source     :
    - https://download.gnome.org/sources/glib/2.76/glib-2.76.4.tar.xz : 5a5a191c96836e166a7771f7ea6ca2b0069c603c7da3cba1cd38d1694a395dda
license    : LGPL-2.1-or-later
summary    : Low level C library containing data structure handling and interfaces
description: |
    GLib is the low-level core library that forms the basis for projects such as GTK+ and GNOME. It provides data structure handling for C, portability wrappers, and interfaces for such runtime functionality as an event loop, threads, dynamic loading, and an object system.
component  : system.base
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(libelf)
    - pkgconfig32(libffi)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(libpcre2-8)
    - pkgconfig32(mount)
    - pkgconfig32(zlib)
setup      : |
    %apply_patches
    %meson_configure -Dgtk_doc=false -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Allow emul32 to work correctly.
    install -Dm00644 $pkgfiles/glibconfig.h $installdir/usr/include/glib-2.0/glibconfig.h
